//Maya Preference 2023 (Release 1)
//
//

optionVar -version 3;

// RecentFiles
optionVar -cat "RecentFiles"
 -sa "RecentFilesList"
 -sva "RecentFilesList" "/home/rapa/pub/Moomins/seq/AFT/AFT_0010/mm/pub/scenes/v001/AFT_0010_mm_v001.mb"
 -sva "RecentFilesList" "/home/rapa/wip/Moomins/seq/AFT/AFT_0010/mm/wip/scenes/v001/AFT_0010_v001_w001.mb"
 -sva "RecentFilesList" "/home/rapa/wip/Moomins/seq/AFT/AFT_0010/ly/wip/scenes/v001/AFT_0010_v001_w003.mb"
 -sva "RecentFilesList" "/home/rapa/wip/Moomins/seq/AFT/AFT_0010/ly/wip/scenes/v001/AFT_0010_v001_w004.mb"
 -sva "RecentFilesList" "/home/rapa/wip/Moomins/seq/AFT/AFT_0010/ly/wip/scenes/v001/AFT_0010_v001_w005.mb"
 -sva "RecentFilesList" "/home/rapa/wip/Moomins/seq/BRK/BRK_0010/lgt/wip/scenes/v001/BRK_0010_v001_w001.mb"
 -sva "RecentFilesList" "/home/rapa/wip/Moomins/seq/BRK/BRK_0010/lgt/wip/scenes/v001/BRK_0010_v001_w003.mb"
 -sva "RecentFilesList" "/home/rapa/wip/Moomins/seq/AFT/AFT_0010/lgt/wip/scenes/v001/AFT_0010_v001_w001.mb"
 -sva "RecentFilesList" "/home/rapa/wip/Moomins/seq/AFT/AFT_0010/lgt/wip/scenes/v001/AFT_0010_v001_w002.mb"
 -sva "RecentFilesList" "/home/rapa/wip/Moomins/seq/AFT/AFT_0010/lgt/wip/scenes/v001/AFT_0010_v001_w003.mb"
 -sa "RecentFilesTypeList"
 -sva "RecentFilesTypeList" "mayaBinary"
 -sva "RecentFilesTypeList" "mayaBinary"
 -sva "RecentFilesTypeList" "mayaBinary"
 -sva "RecentFilesTypeList" "mayaBinary"
 -sva "RecentFilesTypeList" "mayaBinary"
 -sva "RecentFilesTypeList" "mayaBinary"
 -sva "RecentFilesTypeList" "mayaBinary"
 -sva "RecentFilesTypeList" "mayaBinary"
 -sva "RecentFilesTypeList" "mayaBinary"
 -sva "RecentFilesTypeList" "mayaBinary"
 ;

